### ISSUE TITLE
Some HTTPS weirdness

### ISSUE THREAD

**Issue by serriere** [TEECOM/blog#8]
`https://labs.teecom.com` loads fine, but `https://labs.teecom.com/blog` fails to load the style sheet due to a mixed content warning:

`Mixed Content: The page at 'https://labs.teecom.com/blog/' was loaded over HTTPS, but requested an insecure stylesheet 'http://labs.teecom.com/blog/css/main.css'. This request has been blocked; the content must be served over HTTPS.`

Seems like we should be able to just toggle the `enforce https` feature on the Github pages setting, but that box is disabled with the message, `Not yet available for your site because the certificate has not finished being issued. Please allow 24 hours for this process to complete.`

**Comment by newswim** [comment]
A quick and naive fix for now could be to hardcode the `site.github.url` to the string `"http://labs.teecom.com/blog/css/main.css"`. It's currently referenced three times in the code base.

**Comment by tommyschaefer** [comment]
From [this thread](https://github.com/github/pages-gem/issues/238), and from your message, Alex, it looks like this will be fixed whenever we can enable the `Enforce HTTPS` option.

For now, we can remove the specific `HTTP` scheme from the resource URL and it will load using whatever scheme `/blog` is requested with.

Nice catch, @serriere!

And thanks for the suggestion, @newswim, but I think the approach listed above is a bit more flexible.
